spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/events}
    username: ${SPRING_DATASOURCE_USERNAME:events-user}
    password: ${SPRING_DATASOURCE_PASSWORD:events-pass}
  #  liquibase:
  #    change-log: classpath:liquibase/master.yaml
  #    enabled: true

  flyway:
    locations: classpath:db/migration

logging:
  level:
    root: INFO
